# emp_file=open("employee1.txt",'a')
# emp_file.write("\nBanana=12 pieces")
# emp_file=open("employee1.txt","r")
# print(emp_file.readlines())
Emp_file=open('employee1.txt','r')
print(Emp_file.readlines())
Emp_file =open('employee1.txt','a')
Emp_file.write("\nMerrick=100")
Emp_file.close()
Emp_file=open('employee1.txt','r')
print(Emp_file.readlines())
